name: Update build environment

on:
  workflow_dispatch:      # Trigger by hand from the UI
  schedule:
    - cron: '0 1 * * *'   # Schedule it every day

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Login to registry
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ci/docker/build-env.Dockerfile
          tags: stabbles/pkg-example:latest