name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: stabbles/pkg-example:latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Spack
        run: |
          /opt/spack/bin/spack --color=always -e ./tools/environments/ci/ repo add ./tools/spack
          /opt/spack/bin/spack --color=always -e ./tools/environments/ci/ concretize
      - name: Build and test
        run: |
          /opt/spack/bin/spack --color=always -e ./tools/environments/ci/ install -v --test=root